version: '3'

services:
  database:
    image: mysql
    container_name: db_symfonyrecipe
    restart: always
    volumes:
      - database-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - dev
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_symfonyrecipe
    restart: always
    depends_on:
      - database
    ports:
      - 8080:80
    environment:
      PMA_HOST: database
    networks:
      - dev

networks:
  dev:

volumes:
  database-data: