version: '3'

services:
  database:
    image: mysql
    container_name: db_symfonyrecipe
    restart: always
    volumes:
      - database-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - dev

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_symfonyrecipe
    restart: always
    depends_on:
      - database
    ports:
      - 8080:80
    environment:
      PMA_HOST: database
    networks:
      - dev
  
  www:
    restart: always
    build: docker
    container_name: www_symfonyrecipe
    ports:
      - "8000:80"
    volumes:
      - ./docker/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www
    networks:
      - dev

networks:
  dev:

volumes:
  database-data: